// Diagram specs for the System Design Components page. See /assets/anim.js for the engine.
(function () {
  const N = (id, label, c, r, sub, kind, extra) => Object.assign({ id, label, c, r, sub, kind }, extra || {});
  const S = {};

  // 1. Client → ... → data
  S.client_flow = { nodes: [N('cl','Client',0,0,'',''), N('dns','DNS',1,0), N('cdn','CDN',2,0), N('lb','Load balancer',3,0), N('app','App servers',4,0), N('cache','Cache',5,0,'','mem'), N('db','Database',5,1,'','db')],
    edges: [['cl','dns'],['dns','cdn'],['cdn','lb'],['lb','app'],['app','cache'],['app','db']],
    frames: [{ cap: 'GET /feed leaves the client and passes through DNS, the CDN and the load balancer before reaching an app server.', send: [{ path: ['cl','dns','cdn','lb','app'], label: 'GET /feed' }] },
             { cap: 'The app server reads from the cache first, and from the database when it has to.', send: [{ path: ['app','cache'], label: 'read' }, { path: ['app','db'], label: 'read', delay: 500 }] }] };

  S.dns_geo = { nodes: [N('in','User in India',0,0,'','client'), N('eu','User in Europe',0,1,'','client'), N('dns','DNS',1,0,'',''), N('dcin','India data center',2,0,'','db'), N('dceu','European data center',2,1,'','db')],
    edges: [['in','dns'],['eu','dns'],['dns','dcin'],['dns','dceu']],
    frames: [{ cap: 'DNS answers the Indian user with the address of the nearby data center.', send: [{ path: ['in','dns','dcin'], label: 'api.example.com' }] },
             { cap: 'The European user gets a different answer for the same name: the closer region.', send: [{ path: ['eu','dns','dceu'], label: 'api.example.com' }] }] };

  S.web_server = { nodes: [N('b','Browser',0,0,'','client'), N('ng','Nginx',1,0,'web server'), N('be','Node.js / Java / Go',2,0,'application server')],
    edges: [['b','ng'],['ng','be']],
    frames: [{ cap: 'A request for a static file is answered by the web server itself.', send: [{ path: ['b','ng'], label: 'GET /logo.png' }, { path: ['ng','b'], label: '200 image', delay: 900, color: 'ok' }] },
             { cap: 'A dynamic request is forwarded to the application server.', send: [{ path: ['b','ng','be'], label: 'POST /orders' }, { path: ['be','ng','b'], label: '201 created', delay: 1600, color: 'ok' }] }] };

  S.lb = { nodes: [N('c','Client',0,1,'','client'), N('lb','Load balancer',1,1), N('a1','App 1',2,0), N('a2','App 2',2,1), N('a3','App 3',2,2)],
    edges: [['c','lb'],['lb','a1'],['lb','a2'],['lb','a3']],
    frames: [{ cap: 'Each incoming request is handed to one of the servers.', send: [{ path: ['c','lb','a1'], label: 'req' }, { path: ['c','lb','a2'], label: 'req', delay: 500 }, { path: ['c','lb','a3'], label: 'req', delay: 1000 }] }] };

  S.lb_rr = { nodes: [N('c','Client',0,1,'','client'), N('lb','Load balancer',1,1,'round robin'), N('a','Server A',2,0), N('b','Server B',2,1), N('d','Server C',2,2)],
    edges: [['c','lb'],['lb','a'],['lb','b'],['lb','d']],
    frames: [{ cap: 'Request 1 → Server A', send: [{ path: ['c','lb','a'], label: '1' }] }, { cap: 'Request 2 → Server B', send: [{ path: ['c','lb','b'], label: '2' }] }, { cap: 'Request 3 → Server C', send: [{ path: ['c','lb','d'], label: '3' }] }, { cap: 'Request 4 → Server A again. Round and round.', send: [{ path: ['c','lb','a'], label: '4' }] }] };

  S.lb_weighted = { nodes: [N('c','Client',0,0,'','client'), N('lb','Load balancer',1,0,'weighted'), N('a','Server A',2,0,'weight 5'), N('b','Server B',2,1,'weight 2')],
    edges: [['c','lb'],['lb','a'],['lb','b']],
    frames: [{ cap: 'Out of every 7 requests, 5 go to the stronger Server A and 2 to Server B.', send: [0,1,2,3,4].map(i => ({ path: ['c','lb','a'], label: String(i+1), delay: i*350 })).concat([5,6].map(i => ({ path: ['c','lb','b'], label: String(i+1), delay: i*350 }))), t: 4200 }] };

  S.l7 = { nodes: [N('c','Client',0,0,'','client'), N('lb','Layer 7 LB',1,0,'reads the URL'), N('p','Payment Service',2,0), N('u','User Service',2,1)],
    edges: [['c','lb'],['lb','p'],['lb','u']],
    frames: [{ cap: '/api/payments is routed to the Payment Service.', send: [{ path: ['c','lb','p'], label: '/api/payments' }] }, { cap: '/api/users is routed to the User Service.', send: [{ path: ['c','lb','u'], label: '/api/users' }] }] };

  S.scale_out = { nodes: [N('one','1 server',0,0,'','',{}), N('s1','Server',2,0,'',''), N('s2','Server',3,0,'','',{hidden:true}), N('s3','Server',4,0,'','',{hidden:true}), N('s4','Server',2,1,'','',{hidden:true}), N('s5','Server',3,1,'','',{hidden:true}), N('s6','Server',4,1,'','',{hidden:true}), N('s7','Server',2,2,'','',{hidden:true}), N('s8','Server',3,2,'','',{hidden:true}), N('s9','Server',4,2,'','',{hidden:true}), N('s10','Server',2,3,'','',{hidden:true})],
    edges: [],
    frames: [{ cap: 'Scaling out: instead of one bigger machine, add more machines.', hide: ['s2','s3','s4','s5','s6','s7','s8','s9','s10'], t: 1200 },
             { show: ['s2','s3'], cap: '3 servers…', t: 900 }, { show: ['s4','s5','s6'], cap: '6 servers…', t: 900 }, { show: ['s7','s8','s9','s10'], cap: '10 servers. Each one is cheap and replaceable.', t: 2000 }] };

  S.reverse_proxy = { nodes: [N('c','Client',0,0,'','client'), N('rp','Reverse proxy',1,0,'TLS, routing, caching'), N('b1','Backend 1',2,0), N('b2','Backend 2',2,1)],
    edges: [['c','rp'],['rp','b1'],['rp','b2']],
    frames: [{ cap: 'The client only ever talks to the proxy; the backends stay hidden behind it.', send: [{ path: ['c','rp','b1'], label: 'https' }, { path: ['c','rp','b2'], label: 'https', delay: 600 }] }] };
  S.forward_proxy = { nodes: [N('c','Client',0,0,'','client'), N('p','Proxy',1,0,'hides the client'), N('i','Internet',2,0,'','db')], edges: [['c','p'],['p','i']],
    frames: [{ cap: 'A forward proxy sits in front of the client. The internet sees the proxy, not the client.', send: [{ path: ['c','p','i'], label: 'request' }] }] };
  S.reverse_proxy2 = { nodes: [N('i','Internet',0,0,'','client'), N('p','Reverse proxy',1,0,'hides the server'), N('b','Backend',2,0)], edges: [['i','p'],['p','b']],
    frames: [{ cap: 'A reverse proxy sits in front of the server. The internet sees the proxy, not the backend.', send: [{ path: ['i','p','b'], label: 'request' }] }] };

  S.gateway = { nodes: [N('c','Client',0,1,'','client'), N('gw','API Gateway',1,1,'auth, limits, routing'), N('u','User Service',2,0), N('o','Order Service',2,1), N('p','Payment Service',2,2)],
    edges: [['c','gw'],['gw','u'],['gw','o'],['gw','p']],
    frames: [{ cap: 'One entry point. The gateway authenticates, rate-limits and routes to the right service.', send: [{ path: ['c','gw','u'], label: 'GET /users/1' }, { path: ['c','gw','o'], label: 'POST /orders', delay: 600 }, { path: ['c','gw','p'], label: 'POST /payments', delay: 1200 }] }] };
  S.gw_users = { nodes: [N('c','Client',0,0,'','client'), N('gw','API Gateway',1,0), N('u','User Service',2,0)], edges: [['c','gw'],['gw','u']], frames: [{ cap: 'GET /users/123 routes to the User Service.', send: [{ path: ['c','gw','u'], label: 'GET /users/123' }] }] };
  S.gw_pay = { nodes: [N('c','Client',0,0,'','client'), N('gw','API Gateway',1,0), N('p','Payment Service',2,0)], edges: [['c','gw'],['gw','p']], frames: [{ cap: 'POST /payments routes to the Payment Service.', send: [{ path: ['c','gw','p'], label: 'POST /payments' }] }] };

  S.cdn_without = { nodes: [N('in','India',0,0,'','client'), N('x','long network trip',1,0,'','ghost'), N('us','USA server',3,0,'','db')], edges: [['in','us',{ label: 'thousands of km' }]],
    frames: [{ cap: 'Without a CDN every request for logo.png crosses the ocean and back.', send: [{ path: ['in','us'], label: 'logo.png', dur: 1600 }, { path: ['us','in'], label: 'image', delay: 1700, dur: 1600, color: 'warn' }] }] };
  S.cdn_with = { nodes: [N('in','India user',0,0,'','client'), N('edge','Nearby CDN edge',1,0,'Mumbai'), N('us','Origin (USA)',3,0,'','db')], edges: [['in','edge'],['edge','us',{ dashed: true, label: 'only on a miss' }]],
    frames: [{ cap: 'First request: the edge does not have the file yet, so it fetches it from the origin once.', send: [{ path: ['in','edge','us'], label: 'logo.png' }, { path: ['us','edge','in'], label: 'image', delay: 1500, color: 'ok' }] },
             { cap: 'Every later request is served from the nearby edge in a few milliseconds.', send: [{ path: ['in','edge'], label: 'logo.png' }, { path: ['edge','in'], label: 'image', delay: 700, color: 'ok' }] }] };

  S.cache_flow = { nodes: [N('app','Application',0,0), N('cache','Cache',1,0,'','mem'), N('db','Database',2,0,'','db')], edges: [['app','cache'],['cache','db',{ dashed: true }]],
    frames: [{ cap: 'Cache hit: the value is in memory, return it in about 1 ms.', send: [{ path: ['app','cache'], label: 'get user:123' }, { path: ['cache','app'], label: 'hit', delay: 700, color: 'ok' }], badges: { cache: 'hit' } },
             { cap: 'Cache miss: go to the database (about 50 ms), then store the result in the cache.', send: [{ path: ['app','cache'], label: 'get user:9' }, { path: ['cache','db'], label: 'miss', delay: 700, color: 'warn' }, { path: ['db','cache','app'], label: 'row', delay: 1500, color: 'ok' }], badges: { cache: 'miss' } }] };
  S.no_cache = { nodes: [N('app','GET user 123',0,0,'','client'), N('db','Database',1,0,'','db')], edges: [['app','db']], frames: [{ cap: 'Every request hits the database.', send: [{ path: ['app','db'], label: '1' }, { path: ['app','db'], label: '2', delay: 400 }, { path: ['app','db'], label: '3', delay: 800 }] }] };
  S.with_cache = { nodes: [N('app','GET user 123',0,0,'','client'), N('r','Redis',1,0,'','mem'), N('db','Database',2,0,'','db')], edges: [['app','r'],['r','db',{ dashed: true, label: 'only if missing' }]],
    frames: [{ cap: 'The first read misses and fills Redis; the next two are served from memory.', send: [{ path: ['app','r','db'], label: '1' }, { path: ['app','r'], label: '2', delay: 1500, color: 'ok' }, { path: ['app','r'], label: '3', delay: 1900, color: 'ok' }] }] };
  S.cache_aside = { nodes: [N('app','Application',0,0), N('c','Read cache',1,0,'','mem'), N('db','DB',2,0,'','db'), N('set','Cache data',1,1,'cache.set(key, data)','mem')], edges: [['app','c'],['c','db',{ dashed: true, label: 'not found' }],['db','set'],['set','app']],
    frames: [{ cap: 'Found: return straight from the cache.', send: [{ path: ['app','c'], label: 'get' }, { path: ['c','app'], label: 'found', delay: 700, color: 'ok' }] },
             { cap: 'Not found: read the database, write the result into the cache, then return it.', send: [{ path: ['app','c','db'], label: 'get' }, { path: ['db','set','app'], label: 'data', delay: 1500, color: 'ok' }] }] };

  S.replication = { nodes: [N('p','Primary',1,0,'','db'), N('r1','Replica 1',0,1,'','db'), N('r2','Replica 2',2,1,'','db')], edges: [['p','r1'],['p','r2']],
    frames: [{ cap: 'Every write to the primary is copied to the replicas, so the data survives a failure.', send: [{ path: ['p','r1'], label: 'copy' }, { path: ['p','r2'], label: 'copy' }] }] };
  S.rw_split = { nodes: [N('w','Write request',0,0,'','client'), N('p','Primary',1,0,'','db'), N('r','Read requests',0,1,'','client'), N('r1','Replica 1',1,1,'','db'), N('r2','Replica 2',2,1,'','db')], edges: [['w','p'],['p','r1',{ dashed: true }],['p','r2',{ dashed: true }],['r','r1'],['r','r2']],
    frames: [{ cap: 'Writes go to the primary and replicate outward.', send: [{ path: ['w','p'], label: 'UPDATE' }, { path: ['p','r1'], label: 'replicate', delay: 700 }, { path: ['p','r2'], label: 'replicate', delay: 700 }] },
             { cap: 'Reads are spread across the replicas. Replication lag means a replica can be slightly behind.', send: [{ path: ['r','r1'], label: 'SELECT' }, { path: ['r','r2'], label: 'SELECT', delay: 400 }] }] };
  S.partition = { nodes: [N('q','Lookup',0,1,'','client'), N('p1','Partition 1',1,0,'users A–F','db'), N('p2','Partition 2',1,1,'users G–M','db'), N('p3','Partition 3',1,2,'users N–Z','db')], edges: [['q','p1'],['q','p2'],['q','p3']],
    frames: [{ cap: '"Alice" lives in partition 1; "Zoe" in partition 3. Each holds only part of the data.', send: [{ path: ['q','p1'], label: 'Alice' }, { path: ['q','p3'], label: 'Zoe', delay: 600 }, { path: ['q','p2'], label: 'Kim', delay: 1200 }] }] };
  S.shard_range = { nodes: [N('q','Router',0,0,'','client'), N('a','Shard A',1,0,'user_id 1 – 1,000,000','db'), N('b','Shard B',1,1,'user_id 1,000,001 – 2,000,000','db')], edges: [['q','a'],['q','b']],
    frames: [{ cap: 'user 42 is in the first range → Shard A; user 1,500,000 → Shard B.', send: [{ path: ['q','a'], label: 'user 42' }, { path: ['q','b'], label: 'user 1,500,000', delay: 600 }] }] };
  S.shard_hash = { nodes: [N('q','hash(user123) % 4',0,1,'= 2','client'), N('s0','Shard 0',1,0,'','db'), N('s1','Shard 1',2,0,'','db'), N('s2','Shard 2',1,2,'','db'), N('s3','Shard 3',2,2,'','db')], edges: [['q','s2']],
    frames: [{ cap: 'The hash of the key picks the shard: user123 lands on Shard 2.', send: [{ path: ['q','s2'], label: 'user123' }], states: { s2: 'ok' } }] };
  S.ring = { kind: 'ring' };

  S.mq = { nodes: [N('o','Order Service',0,1), N('q','Message queue',1,1,'','queue'), N('e','Email',2,0), N('a','Analytics',2,1), N('w','Warehouse',2,2)], edges: [['o','q'],['q','e'],['q','a'],['q','w']],
    frames: [{ cap: 'The order service drops one message and returns immediately. Workers pick it up in the background.', send: [{ path: ['o','q'], label: 'OrderCreated' }, { path: ['q','e'], label: 'send mail', delay: 900 }, { path: ['q','a'], label: 'record', delay: 1100 }, { path: ['q','w'], label: 'pack', delay: 1300 }] }] };
  S.prod_cons = { nodes: [N('o','Order Service',0,0), N('p','Producer',1,0), N('q','Queue',2,0,'','queue'), N('c','Consumer',3,0), N('e','Email Service',4,0)], edges: [['o','p'],['p','q'],['q','c'],['c','e']],
    frames: [{ cap: 'Producer puts OrderCreated on the queue; a consumer takes it off and acts on it.', send: [{ path: ['o','p','q'], label: 'OrderCreated' }, { path: ['q','c','e'], label: 'OrderCreated', delay: 1500 }] }] };
  S.event_driven = { nodes: [N('ev','OrderCreated',0,1,'event','queue'), N('p','Payment Service',1,0), N('i','Inventory Service',2,0), N('e','Email Service',1,2), N('a','Analytics Service',2,2)], edges: [['ev','p'],['ev','i'],['ev','e'],['ev','a']],
    frames: [{ cap: 'One event, four listeners. The publisher does not know or care who is listening.', send: [{ path: ['ev','p'], label: '' }, { path: ['ev','i'], label: '', delay: 150 }, { path: ['ev','e'], label: '', delay: 300 }, { path: ['ev','a'], label: '', delay: 450 }] }] };
  S.kafka = { nodes: [N('p','Producer',0,1), N('t','Topic',1,1,'','queue'), N('p0','Partition 0',2,0,'','queue'), N('p1','Partition 1',2,1,'','queue'), N('p2','Partition 2',2,2,'','queue'), N('c','Consumers',3,1)], edges: [['p','t'],['t','p0'],['t','p1'],['t','p2'],['p0','c'],['p1','c'],['p2','c']],
    frames: [{ cap: 'Events are appended to partitions of a topic; consumers read them, and can re-read them later.', send: [{ path: ['p','t','p0','c'], label: 'e1' }, { path: ['p','t','p1','c'], label: 'e2', delay: 400 }, { path: ['p','t','p2','c'], label: 'e3', delay: 800 }] }] };
  S.queue_plain = { nodes: [N('p','Producer',0,0), N('q','Queue',1,0,'','queue'), N('c','Consumer',2,0)], edges: [['p','q'],['q','c']],
    frames: [{ cap: 'Message goes in…', send: [{ path: ['p','q'], label: 'msg' }], badges: { q: '1 waiting' } }, { cap: '…consumer processes it, and it is gone from the queue.', send: [{ path: ['q','c'], label: 'msg' }], badges: { q: '0 waiting' } }] };
  S.event_log = { nodes: [N('e1','Event 1',0,0,'','queue'), N('e2','Event 2',1,0,'','queue'), N('e3','Event 3',2,0,'','queue'), N('e4','Event 4',3,0,'','queue'), N('e5','Event 5',4,0,'','queue'), N('ca','Consumer A',1,1), N('cb','Consumer B',3,1)], edges: [],
    frames: [{ cap: 'Events stay in the log. Consumer A is at event 2, consumer B is already at event 4.', states: { e2: 'on', e4: 'ok' }, badges: { e2: 'A', e4: 'B' }, t: 1800 },
             { cap: 'Each consumer advances its own position at its own pace.', states: { e3: 'on', e5: 'ok' }, badges: { e3: 'A', e5: 'B' }, t: 1800 },
             { cap: 'Consumer A can even rewind to event 1 and replay history. Nothing was deleted.', states: { e1: 'on', e5: 'ok' }, badges: { e1: 'A', e5: 'B' }, t: 2200 }] };
  S.pubsub = { nodes: [N('ev','OrderCreated',0,1,'','queue'), N('e','Email Service',1,0), N('a','Analytics Service',1,1), N('i','Inventory Service',1,2)], edges: [['ev','e'],['ev','a'],['ev','i']],
    frames: [{ cap: 'Pub/Sub: the same event is delivered to every subscriber.', send: [{ path: ['ev','e'], label: 'copy' }, { path: ['ev','a'], label: 'copy', delay: 150 }, { path: ['ev','i'], label: 'copy', delay: 300 }] }] };
  S.retry_chain = { nodes: [N('q','Main queue',0,0,'','queue'), N('w','Process payment',1,0), N('dlq','Dead letter queue',1,2,'','queue')], edges: [['q','w'],['w','q',{ dashed: true, label: 'retry' }],['w','dlq',{ dashed: true }]],
    frames: [{ cap: 'Attempt 1 fails.', send: [{ path: ['q','w'], label: 'msg' }], states: { w: 'fail' } }, { cap: 'Retry. Attempt 2 fails.', send: [{ path: ['q','w'], label: 'msg' }], states: { w: 'fail' } }, { cap: 'Retry. Attempt 3 fails.', send: [{ path: ['q','w'], label: 'msg' }], states: { w: 'fail' } },
             { cap: 'After repeated failures the message is parked in the dead letter queue for a human to inspect.', send: [{ path: ['w','dlq'], label: 'msg', color: 'warn' }], states: {} }] };
  S.dlq = { nodes: [N('q','Main queue',0,0,'','queue'), N('w','Worker',1,0), N('dlq','Dead letter queue',2,0,'','queue')], edges: [['q','w'],['w','dlq',{ label: 'failed repeatedly' }]],
    frames: [{ cap: 'Normal messages are processed; the one that keeps failing is moved aside instead of blocking the queue.', send: [{ path: ['q','w'], label: 'ok', color: 'ok' }, { path: ['q','w','dlq'], label: 'bad', delay: 900, color: 'warn' }] }] };
  S.backoff = { kind: 'backoff' };
  S.ratelimit = { nodes: [N('c','Client',0,0,'','client'), N('rl','Rate limiter',1,0,'100 / minute'), N('api','API',2,0)], edges: [['c','rl'],['rl','api']],
    frames: [{ cap: 'Requests within the limit pass through.', send: [{ path: ['c','rl','api'], label: '98' }, { path: ['c','rl','api'], label: '99', delay: 400 }, { path: ['c','rl','api'], label: '100', delay: 800 }] },
             { cap: 'The 101st request is answered with 429 Too Many Requests and never reaches the API.', send: [{ path: ['c','rl'], label: '101' }, { path: ['rl','c'], label: '429', delay: 700, color: 'fail' }], states: { rl: 'fail' } }] };
  S.bucket = { kind: 'bucket' };
  S.session = { nodes: [N('a1','App server 1',0,0), N('a2','App server 2',1,0), N('a3','App server 3',2,0), N('r','Redis',1,1,'shared sessions','mem')], edges: [['a1','r'],['a2','r'],['a3','r']],
    frames: [{ cap: 'Login on server 1 stores the session in Redis…', send: [{ path: ['a1','r'], label: 'abc123 → 42' }] }, { cap: '…so the next request, landing on server 3, can still find it.', send: [{ path: ['a3','r'], label: 'abc123?' }, { path: ['r','a3'], label: 'user 42', delay: 700, color: 'ok' }] }] };
  S.object_storage = { nodes: [N('app','Application',0,0), N('os','Object storage',1,0,'S3 / GCS / Blob','db'), N('cdn','CDN',2,0), N('u','Users',3,0,'','client')], edges: [['app','os'],['os','cdn'],['cdn','u']],
    frames: [{ cap: 'The app uploads a video once; the CDN pulls it from storage and serves it to users nearby.', send: [{ path: ['app','os'], label: 'upload' }, { path: ['os','cdn','u'], label: 'video', delay: 900, color: 'ok' }] }] };
  S.search = { nodes: [N('db','Primary database',0,0,'source of truth','db'), N('ix','Search index',1,0,'Elasticsearch','mem'), N('api','Search API',2,0), N('u','User',3,0,'','client')], edges: [['db','ix',{ label: 'sync' }],['api','ix'],['u','api']],
    frames: [{ cap: 'Changes in the database are synced into the index.', send: [{ path: ['db','ix'], label: 'new product' }] }, { cap: 'Searches hit the index, which ranks, tolerates typos and filters fast.', send: [{ path: ['u','api','ix'], label: '"wireles headphone"' }, { path: ['ix','api','u'], label: 'results', delay: 1500, color: 'ok' }] }] };
  S.discovery = { nodes: [N('o','Order Service',0,0), N('reg','Service registry',1,0), N('p1','Payment 10.1.0.4',2,0), N('p2','Payment 10.1.0.8',2,1), N('p3','Payment 10.1.0.11',2,2)], edges: [['o','reg'],['reg','p1',{ dashed: true }],['reg','p2',{ dashed: true }],['reg','p3',{ dashed: true }],['o','p2',{ hidden: true }]],
    frames: [{ cap: 'Instances register themselves and send heartbeats.', send: [{ path: ['p1','reg'], label: 'I am here' }, { path: ['p2','reg'], label: 'I am here', delay: 200 }, { path: ['p3','reg'], label: 'I am here', delay: 400 }] },
             { cap: 'The order service asks "where is payment?" and gets a current address.', send: [{ path: ['o','reg'], label: 'payment?' }, { path: ['reg','o'], label: '10.1.0.8', delay: 700, color: 'ok' }] },
             { cap: 'Then it calls that instance directly.', send: [{ path: ['o','p2'], label: 'charge' }] }] };
  S.monolith = { nodes: [N('g','Application',0,0,'','group',{ w: 3, h: 2 }), N('u','Users',0,0), N('o','Orders',1,0), N('p','Payments',2,0), N('i','Inventory',0,1), N('n','Notifications',1,1), N('db','Database',1,2,'','db')], edges: [['n','db']],
    frames: [{ cap: 'Everything is one deployable unit: modules call each other in-process and share one database.', send: [{ path: ['u','o'], label: 'call' }, { path: ['o','p'], label: 'call', delay: 500 }, { path: ['n','db'], label: 'query', delay: 1000 }] }] };
  S.mesh = { nodes: [N('a','Service A',0,0), N('pa','Proxy',1,0,'sidecar'), N('pb','Proxy',2,0,'sidecar'), N('b','Service B',3,0)], edges: [['a','pa'],['pa','pb',{ label: 'mTLS, retries, metrics' }],['pb','b']],
    frames: [{ cap: 'Each service talks only to its own sidecar proxy. The proxies handle TLS, retries and tracing between them.', send: [{ path: ['a','pa','pb','b'], label: 'call' }] }] };
  S.breaker_flow = { nodes: [N('o','Order Service',0,0), N('p','Payment Service',1,0)], edges: [['o','p']],
    frames: [{ cap: 'Calls succeed.', send: [{ path: ['o','p'], label: 'charge' }, { path: ['p','o'], label: 'ok', delay: 700, color: 'ok' }] }, { cap: 'Payment goes down. Every call now waits and fails, tying up resources.', states: { p: 'fail' }, send: [{ path: ['o','p'], label: 'charge', color: 'fail' }, { path: ['o','p'], label: 'charge', delay: 300, color: 'fail' }, { path: ['o','p'], label: 'charge', delay: 600, color: 'fail' }] }] };
  S.breaker = { nodes: [N('o','Order Service',0,0), N('cb','Circuit breaker',1,0,'CLOSED'), N('p','Payment Service',2,0)], edges: [['o','cb'],['cb','p']],
    frames: [{ cap: 'CLOSED: requests flow normally.', labels: { cb: 'CLOSED' }, states: { cb: 'ok' }, send: [{ path: ['o','cb','p'], label: 'req' }, { path: ['p','cb','o'], label: 'ok', delay: 1400, color: 'ok' }] },
             { cap: 'Failures start. The breaker counts them.', states: { cb: 'ok', p: 'fail' }, badges: { cb: '3 failures' }, send: [{ path: ['o','cb','p'], label: 'req' }, { path: ['p','cb','o'], label: 'error', delay: 1400, color: 'fail' }] },
             { cap: 'OPEN: too many failures. Requests fail instantly without touching the broken service.', labels: { cb: 'OPEN' }, states: { cb: 'fail', p: 'fail' }, badges: {}, send: [{ path: ['o','cb'], label: 'req' }, { path: ['cb','o'], label: 'fail fast', delay: 700, color: 'fail' }, { path: ['o','cb'], label: 'req', delay: 1000 }, { path: ['cb','o'], label: 'fail fast', delay: 1700, color: 'fail' }] },
             { cap: 'HALF-OPEN: after a timeout, one test request is let through.', labels: { cb: 'HALF-OPEN' }, states: { cb: 'warn' }, send: [{ path: ['o','cb','p'], label: 'test' }, { path: ['p','cb','o'], label: 'ok', delay: 1400, color: 'ok' }] },
             { cap: 'It succeeded, so the circuit closes again.', labels: { cb: 'CLOSED' }, states: { cb: 'ok' }, send: [{ path: ['o','cb','p'], label: 'req' }], t: 2200 }] };
  S.health = { nodes: [N('lb','Load balancer',0,1), N('a','Server A',1,0), N('b','Server B',1,1), N('c','Server C',1,2)], edges: [['lb','a'],['lb','b'],['lb','c']],
    frames: [{ cap: 'The load balancer probes GET /health on every server.', send: [{ path: ['lb','a'], label: '/health' }, { path: ['lb','b'], label: '/health' }, { path: ['lb','c'], label: '/health' }], states: {} },
             { cap: 'Server B stops answering.', states: { b: 'fail' }, send: [{ path: ['lb','b'], label: '/health', color: 'fail' }], badges: { b: 'no reply' } },
             { cap: 'It is marked unhealthy and taken out of rotation. Traffic flows only to A and C.', states: { b: 'off' }, badges: { b: 'unhealthy' }, send: [{ path: ['lb','a'], label: 'req' }, { path: ['lb','c'], label: 'req', delay: 400 }, { path: ['lb','a'], label: 'req', delay: 800 }] }] };
  S.heartbeat = { nodes: [N('s','Server',0,0), N('co','Coordinator',1,0)], edges: [['s','co']],
    frames: [{ cap: 'Every few seconds: "I am still alive."', send: [{ path: ['s','co'], label: '♥' }, { path: ['s','co'], label: '♥', delay: 600 }, { path: ['s','co'], label: '♥', delay: 1200 }] },
             { cap: 'The heartbeats stop…', states: { s: 'fail' }, badges: { co: 'waiting…' }, t: 1800 },
             { cap: '…and after a timeout the coordinator declares the server dead.', states: { s: 'off' }, badges: { co: 'server unavailable' }, t: 2000 }] };
  S.leader = { nodes: [N('a','Node A',0,0), N('b','Node B',1,0), N('c','Node C',2,0)], edges: [],
    frames: [{ cap: 'Node A is the leader; B and C follow.', states: { a: 'ok' }, badges: { a: 'leader', b: 'follower', c: 'follower' }, t: 2000 },
             { cap: 'The leader fails.', states: { a: 'fail' }, badges: { a: 'down', b: 'follower', c: 'follower' }, t: 1600 },
             { cap: 'The remaining nodes elect a new leader. Only one node runs the scheduled job at a time.', states: { a: 'off', c: 'ok' }, badges: { a: 'down', b: 'follower', c: 'leader' }, t: 2400 }] };
  S.lock = { nodes: [N('a','Server A',0,0), N('b','Server B',0,1), N('l','Lock service',1,0), N('inv','Inventory',2,0,'','db')], edges: [['a','l'],['b','l'],['l','inv',{ hidden: true }],['a','inv',{ hidden: true }],['b','inv',{ hidden: true }]],
    frames: [{ cap: 'Both servers want to update inventory. A asks for the lock first and gets it.', send: [{ path: ['a','l'], label: 'lock?' }, { path: ['l','a'], label: 'granted', delay: 700, color: 'ok' }], states: { a: 'ok' } },
             { cap: 'B asks too, but the lock is held: B must wait (or give up).', send: [{ path: ['b','l'], label: 'lock?' }, { path: ['l','b'], label: 'busy', delay: 700, color: 'warn' }], states: { a: 'ok', b: 'warn' } },
             { cap: 'A does its update and releases the lock.', send: [{ path: ['a','inv'], label: 'update' }, { path: ['a','l'], label: 'release', delay: 900 }], states: { b: 'warn' } },
             { cap: 'Now B can take the lock and do its update, one at a time.', send: [{ path: ['b','l'], label: 'lock?' }, { path: ['l','b'], label: 'granted', delay: 700, color: 'ok' }, { path: ['b','inv'], label: 'update', delay: 1500 }], states: { b: 'ok' } }] };
  S.saga = { nodes: [N('s1','1 Create order',0,0), N('s2','2 Reserve inventory',1,0), N('s3','3 Charge payment',2,0), N('s4','4 Arrange shipment',3,0), N('c2','Release inventory',1,1,'compensate'), N('c1','Cancel order',0,1,'compensate')], edges: [['s1','s2'],['s2','s3'],['s3','s4'],['s3','c2',{ dashed: true }],['c2','c1',{ dashed: true }]],
    frames: [{ cap: 'Each step is its own local transaction.', states: { s1: 'ok' }, send: [{ path: ['s1','s2'], label: '' }] }, { states: { s1: 'ok', s2: 'ok' }, cap: 'Inventory reserved…', send: [{ path: ['s2','s3'], label: '' }] },
             { cap: 'Payment fails. There is no global rollback…', states: { s1: 'ok', s2: 'ok', s3: 'fail' }, t: 1600 },
             { cap: '…so compensating actions run backwards: release the inventory, then cancel the order.', states: { s3: 'fail', c2: 'warn' }, send: [{ path: ['s3','c2'], label: 'undo', color: 'warn' }] },
             { states: { s3: 'fail', c2: 'warn', c1: 'warn' }, cap: 'The system is consistent again.', send: [{ path: ['c2','c1'], label: 'undo', color: 'warn' }], t: 2200 }] };
  S.read_replica = { nodes: [N('p','Primary',1,0,'','db'), N('r1','Read 1',0,1,'','db'), N('r2','Read 2',1,1,'','db'), N('r3','Read 3',2,1,'','db')], edges: [['p','r1'],['p','r2'],['p','r3']],
    frames: [{ cap: 'Writes go to the primary; the replicas copy them.', send: [{ path: ['p','r1'], label: 'copy' }, { path: ['p','r2'], label: 'copy' }, { path: ['p','r3'], label: 'copy' }], badges: { p: 'writes' } }, { cap: 'Reads are spread across all three replicas.', badges: { r1: 'reads', r2: 'reads', r3: 'reads' }, states: { r1: 'ok', r2: 'ok', r3: 'ok' }, t: 2000 }] };
  S.cqrs = { nodes: [N('w','Write API',0,0), N('tdb','Transactional DB',1,0,'','db'), N('ev','Events',2,0,'','queue'), N('rdb','Read DB',3,0,'optimised for queries','db'), N('r','Read API',4,0)], edges: [['w','tdb'],['tdb','ev'],['ev','rdb'],['r','rdb']],
    frames: [{ cap: 'A command is written to the transactional store, which emits an event that updates the read model.', send: [{ path: ['w','tdb','ev','rdb'], label: 'OrderPlaced' }] }, { cap: 'Queries hit the read model, shaped exactly for fast reads.', send: [{ path: ['r','rdb'], label: 'query' }, { path: ['rdb','r'], label: 'view', delay: 700, color: 'ok' }] }] };
  S.event_sourcing = { nodes: [N('e1','AccountCreated',0,0,'','queue'), N('e2','Deposit ₹5,000',1,0,'','queue'), N('e3','Deposit ₹7,000',2,0,'','queue'), N('e4','Withdraw ₹2,000',3,0,'','queue'), N('st','Balance',1,1,'₹0','db',{ w: 2 })], edges: [['e1','st'],['e2','st'],['e3','st'],['e4','st']],
    frames: [{ cap: 'Replay the events in order to rebuild the state.', labels: { st: 'Balance ₹0' }, send: [{ path: ['e1','st'], label: '' }], states: { e1: 'on' } }, { labels: { st: 'Balance ₹5,000' }, send: [{ path: ['e2','st'], label: '+5,000' }], states: { e1: 'on', e2: 'on' } }, { labels: { st: 'Balance ₹12,000' }, send: [{ path: ['e3','st'], label: '+7,000' }], states: { e1: 'on', e2: 'on', e3: 'on' } }, { cap: 'Current state is just the sum of history, and the history is never lost.', labels: { st: 'Balance ₹10,000' }, send: [{ path: ['e4','st'], label: '−2,000' }], states: { e1: 'on', e2: 'on', e3: 'on', e4: 'on' }, t: 2400 }] };
  S.cap = { nodes: [N('c','Client',0,0,'','client'), N('a','Node A',1,0,'','db'), N('b','Node B',2,0,'','db'), N('x','partition',1,1,'network split','ghost',{ w: 2 })], edges: [['c','a'],['a','b',{ both: true }]],
    frames: [{ cap: 'Normally nodes replicate to each other and every read sees the latest write.', send: [{ path: ['c','a'], label: 'write' }, { path: ['a','b'], label: 'replicate', delay: 700 }] },
             { cap: 'The network between A and B breaks. Now you must choose.', states: { x: 'fail' }, edgesHide: ['a>b'], t: 1800 },
             { cap: 'Choose Consistency: refuse writes that cannot be replicated. Correct, but unavailable.', states: { x: 'fail', a: 'fail' }, send: [{ path: ['c','a'], label: 'write' }, { path: ['a','c'], label: 'rejected', delay: 700, color: 'fail' }] },
             { cap: 'Choose Availability: accept the write on A alone. Available, but B is now stale.', states: { x: 'fail', a: 'ok', b: 'warn' }, send: [{ path: ['c','a'], label: 'write' }, { path: ['a','c'], label: 'ok', delay: 700, color: 'ok' }], badges: { b: 'stale' }, t: 2600 },
             { cap: 'Partition heals; replication resumes.', states: {}, edgesShow: ['a>b'], badges: {}, send: [{ path: ['a','b'], label: 'catch up' }] }] };
  S.failover = { nodes: [N('app','Application',0,0), N('a','Primary A',1,0,'','db'), N('b','Replica B',1,1,'','db')], edges: [['app','a'],['a','b'],['app','b',{ hidden: true }]],
    frames: [{ cap: 'Writes go to A; B replicates.', send: [{ path: ['app','a'], label: 'write' }, { path: ['a','b'], label: 'copy', delay: 700 }], states: { a: 'ok' }, badges: { a: 'primary', b: 'replica' } },
             { cap: 'A fails.', states: { a: 'fail' }, badges: { a: 'down', b: 'replica' }, t: 1500 },
             { cap: 'Failover: B is promoted to primary and the app is pointed at it.', states: { a: 'off', b: 'ok' }, badges: { a: 'down', b: 'primary' }, edgesHide: ['app>a','a>b'], edgesShow: ['app>b'], send: [{ path: ['app','b'], label: 'write' }], t: 2600 },
             { states: {}, badges: { a: 'primary', b: 'replica' }, edgesShow: ['app>a','a>b'], edgesHide: ['app>b'], t: 600 }] };
  S.spof_bad = { nodes: [N('u','Users',0,0,'','client'), N('s','One server',1,0), N('db','One database',2,0,'','db')], edges: [['u','s'],['s','db']],
    frames: [{ cap: 'It works…', send: [{ path: ['u','s','db'], label: 'req' }] }, { cap: '…until the only server dies, and every user is down.', states: { s: 'fail', u: 'warn' }, send: [{ path: ['u','s'], label: 'req', color: 'fail' }], t: 2400 }] };
  S.spof_good = { nodes: [N('u','Users',0,1,'','client'), N('lb','Load balancer',1,1), N('a1','App 1',2,0), N('a2','App 2',2,2), N('db','Database cluster',3,1,'','db')], edges: [['u','lb'],['lb','a1'],['lb','a2'],['a1','db'],['a2','db']],
    frames: [{ cap: 'Traffic is spread over two app servers and a clustered database.', send: [{ path: ['u','lb','a1','db'], label: 'req' }, { path: ['u','lb','a2','db'], label: 'req', delay: 500 }] }, { cap: 'App 1 dies. The load balancer routes everything to App 2; users notice nothing.', states: { a1: 'off' }, send: [{ path: ['u','lb','a2','db'], label: 'req' }, { path: ['u','lb','a2','db'], label: 'req', delay: 500 }], t: 2800 }] };
  S.multi_region = { nodes: [N('g','Global routing',1,0,'DNS / anycast'), N('inr','India region',0,1,'','group',{ w: 1, h: 2 }), N('usr','US region',2,1,'','group',{ w: 1, h: 2 }), N('inapp','App',0,1), N('indb','DB',0,2,'','db'), N('usapp','App',2,1), N('usdb','DB',2,2,'','db')], edges: [['g','inapp'],['g','usapp'],['inapp','indb'],['usapp','usdb'],['indb','usdb',{ dashed: true, label: 'cross-region replication' }]],
    frames: [{ cap: 'Users are routed to the nearest region; each region has its own app and database.', send: [{ path: ['g','inapp','indb'], label: 'IN user' }, { path: ['g','usapp','usdb'], label: 'US user', delay: 400 }] }, { cap: 'Data replicates between regions so either can take over in a disaster.', send: [{ path: ['indb','usdb'], label: 'replicate' }] }] };
  S.az = { nodes: [N('r','Region',1,0,'','group',{ w: 1, h: 1 }), N('lb','Load balancer',1,0), N('z1','AZ-1',0,1,'servers'), N('z2','AZ-2',1,1,'servers'), N('z3','AZ-3',2,1,'servers')], edges: [['lb','z1'],['lb','z2'],['lb','z3']],
    frames: [{ cap: 'Servers are spread across three physically separate zones.', send: [{ path: ['lb','z1'], label: '' }, { path: ['lb','z2'], label: '' }, { path: ['lb','z3'], label: '' }] }, { cap: 'AZ-2 loses power. The other two zones carry on.', states: { z2: 'off' }, send: [{ path: ['lb','z1'], label: '' }, { path: ['lb','z3'], label: '', delay: 300 }], t: 2600 }] };
  S.autoscale = { nodes: [N('m','Traffic',0,1,'10 req/s at 3 AM','client'), N('s1','Server',1,0), N('s2','Server',1,1), N('s3','Server',1,2), N('s4','Server',2,0,'','',{ hidden: true }), N('s5','Server',2,1,'','',{ hidden: true }), N('s6','Server',2,2,'','',{ hidden: true }), N('s7','Server',3,0,'','',{ hidden: true }), N('s8','Server',3,1,'','',{ hidden: true }), N('s9','Server',3,2,'','',{ hidden: true })], edges: [],
    frames: [{ cap: 'Low traffic: 3 servers are plenty.', labels: { m: '10 req/s, 3 AM' }, hide: ['s4','s5','s6','s7','s8','s9'], t: 2000 }, { cap: 'Evening peak: CPU climbs, autoscaling adds capacity…', labels: { m: '10,000 req/s, 8 PM' }, show: ['s4','s5','s6'], t: 1400 }, { show: ['s7','s8','s9'], cap: '…up to 9 servers (the guide says 30; same idea).', t: 2000 }, { cap: 'Traffic falls, servers are removed again. You only pay for what you use.', labels: { m: '500 req/s, midnight' }, hide: ['s6','s7','s8','s9'], t: 2400 }] };
  S.container = { nodes: [N('dev','Developer laptop',0,0,'','client'), N('img','Docker image',1,0,'app + runtime + libs','queue'), N('prod','Production server',2,0)], edges: [['dev','img'],['img','prod']],
    frames: [{ cap: 'The app and everything it needs are packaged once…', send: [{ path: ['dev','img'], label: 'build' }] }, { cap: '…and that exact package runs the same way in production.', send: [{ path: ['img','prod'], label: 'run' }], states: { prod: 'ok' } }] };
  S.stateless = { nodes: [N('c','Client',0,1,'','client'), N('lb','LB',1,1), N('a','Server A',2,0), N('b','Server B',2,1), N('d','Server C',2,2), N('r','Redis / DB',3,1,'shared state','mem')], edges: [['c','lb'],['lb','a'],['lb','b'],['lb','d'],['a','r'],['b','r'],['d','r']],
    frames: [{ cap: 'Request 1 → A, request 2 → C, request 3 → B. Any server works because the state lives in shared storage, not in server memory.', send: [{ path: ['c','lb','a','r'], label: '1' }, { path: ['c','lb','d','r'], label: '2', delay: 600 }, { path: ['c','lb','b','r'], label: '3', delay: 1200 }] }] };
  S.stream = { nodes: [N('src','Events',0,0,'continuous','queue'), N('sp','Stream processor',1,0,'Flink / Kafka Streams'), N('out','Dashboard / alerts',2,0)], edges: [['src','sp'],['sp','out']],
    frames: [{ cap: 'Events are processed as they arrive, one after another, with no nightly batch.', send: [{ path: ['src','sp','out'], label: 'e' }, { path: ['src','sp','out'], label: 'e', delay: 300 }, { path: ['src','sp','out'], label: 'e', delay: 600 }, { path: ['src','sp','out'], label: 'e', delay: 900 }] }] };
  S.scheduler = { nodes: [N('s','Scheduler',0,0,'2:00 AM daily'), N('q','Job queue',1,0,'','queue'), N('w','Workers',2,0)], edges: [['s','q'],['q','w']],
    frames: [{ cap: 'At the scheduled time the scheduler enqueues the job; workers pick it up.', send: [{ path: ['s','q'], label: 'daily report' }, { path: ['q','w'], label: 'daily report', delay: 900 }] }] };
  S.worker = { nodes: [N('q','Queue',0,0,'GenerateThumbnail(image_123)','queue'), N('w','Worker',1,0), N('rz','Resize image',2,0), N('st','Store result',3,0,'','db')], edges: [['q','w'],['w','rz'],['rz','st']],
    frames: [{ cap: 'A worker takes a task off the queue, does the work, stores the result, and goes back for the next one.', send: [{ path: ['q','w','rz','st'], label: 'image_123' }] }] };
  S.http = { nodes: [N('c','Client',0,0,'','client'), N('s','Server',2,0)], edges: [['c','s',{ both: true }]],
    frames: [{ cap: 'Plain HTTP: the client asks, the server answers, the connection is done.', send: [{ path: ['c','s'], label: 'request' }, { path: ['s','c'], label: 'response', delay: 800, color: 'ok' }], t: 2600 }] };
  S.websocket = { nodes: [N('c','Client',0,0,'','client'), N('s','Server',2,0)], edges: [['c','s',{ both: true, label: 'one long-lived connection' }]],
    frames: [{ cap: 'WebSocket: either side can send at any time over the same open connection.', send: [{ path: ['c','s'], label: 'hi' }, { path: ['s','c'], label: 'new msg', delay: 500, color: 'ok' }, { path: ['s','c'], label: 'new msg', delay: 1000, color: 'ok' }, { path: ['c','s'], label: 'typing…', delay: 1300 }] }] };
  S.sse = { nodes: [N('s','Server',0,0), N('c','Client',2,0,'','client')], edges: [['s','c',{ label: 'one-way stream' }]],
    frames: [{ cap: 'Server-Sent Events: the server keeps pushing updates; the client just listens.', send: [{ path: ['s','c'], label: 'update' }, { path: ['s','c'], label: 'update', delay: 500 }, { path: ['s','c'], label: 'update', delay: 1000 }] }] };
  S.longpoll = { nodes: [N('c','Client',0,0,'','client'), N('s','Server',2,0)], edges: [['c','s',{ both: true }]],
    frames: [{ cap: 'Long polling: "any new messages?" The server holds the request open…', send: [{ path: ['c','s'], label: 'any new?' }], badges: { s: 'holding…' }, t: 2200 }, { cap: '…until something arrives, then answers. The client immediately asks again.', send: [{ path: ['s','c'], label: 'msg', color: 'ok' }, { path: ['c','s'], label: 'any new?', delay: 800 }], badges: {} }] };
  S.bloom = { nodes: [N('q','Lookup',0,0,'','client'), N('bf','Bloom filter',1,0,'tiny, in memory','mem'), N('db','Database',2,0,'','db')], edges: [['q','bf'],['bf','db',{ dashed: true, label: 'maybe' }]],
    frames: [{ cap: '"Definitely not there": stop immediately, no database call.', send: [{ path: ['q','bf'], label: 'key 7?' }, { path: ['bf','q'], label: 'no', delay: 700, color: 'fail' }] }, { cap: '"Might be there": check the database (and sometimes it turns out not to be: a false positive).', send: [{ path: ['q','bf','db'], label: 'key 42?' }, { path: ['db','bf','q'], label: 'found', delay: 1500, color: 'ok' }] }] };
  S.pool = { nodes: [N('app','Application',0,1), N('c1','C1',1,0,'','mem'), N('c2','C2',1,1,'','mem'), N('c3','C3',1,2,'','mem'), N('db','Database',2,1,'','db')], edges: [['app','c1'],['app','c2'],['app','c3'],['c1','db'],['c2','db'],['c3','db']],
    frames: [{ cap: 'Three open connections are kept ready. Requests borrow one…', send: [{ path: ['app','c1','db'], label: 'q1' }, { path: ['app','c3','db'], label: 'q2', delay: 400 }], states: { c1: 'on', c3: 'on' } }, { cap: '…and return it when done, so no new connection has to be opened.', send: [{ path: ['db','c1','app'], label: 'rows', color: 'ok' }, { path: ['db','c3','app'], label: 'rows', delay: 300, color: 'ok' }], states: {} }] };
  S.grpc = { nodes: [N('c','External client',0,0,'','client'), N('gw','API Gateway',1,0), N('s1','Internal service',2,0), N('s2','Internal service',2,1)], edges: [['c','gw',{ label: 'REST' }],['gw','s1',{ label: 'gRPC' }],['gw','s2',{ label: 'gRPC' }]],
    frames: [{ cap: 'REST and JSON at the edge for humans and browsers; gRPC and Protocol Buffers between services for speed.', send: [{ path: ['c','gw','s1'], label: 'JSON → protobuf' }, { path: ['gw','s2'], label: 'protobuf', delay: 1300 }] }] };
  S.trace_flow = { nodes: [N('gw','API Gateway',0,0), N('u','User Service',1,0), N('o','Order Service',2,0), N('p','Payment Service',3,0), N('db','Database',4,0,'','db')], edges: [['gw','u'],['u','o'],['o','p'],['p','db']],
    frames: [{ cap: 'One request, one trace id carried through every hop.', send: [{ path: ['gw','u','o','p','db'], label: 'trace 8f3a' }] }] };
  S.trace_waterfall = { kind: 'waterfall', rows: [{ label: 'API Gateway', ms: 30, text: '30 ms' }, { label: 'Order Service', ms: 100, text: '100 ms' }, { label: 'Payment Service', ms: 2100, text: '2.1 s', hot: true }, { label: 'Database', ms: 50, text: '50 ms' }], cap0: 'Total: 2.4 seconds. Where did it go?', cap1: 'Payment Service took 2.1 of the 2.4 seconds. The bottleneck is obvious once you can see the trace.' };
  S.latency = { nodes: [N('c','Request sent',0,0,'','client'), N('s','Server',2,0)], edges: [['c','s',{ both: true, label: '100 ms round trip' }]],
    frames: [{ cap: 'Latency is the time from sending the request to receiving the response.', send: [{ path: ['c','s'], label: '', dur: 900 }, { path: ['s','c'], label: 'response', delay: 1000, dur: 900, color: 'ok' }] }] };
  S.percentile = { kind: 'percentile' };
  S.backpressure = { nodes: [N('p','Producers',0,0,'100,000 events/s'), N('q','Queue',1,0,'','queue'), N('c','Consumers',2,0,'10,000 events/s')], edges: [['p','q'],['q','c']],
    frames: [{ cap: 'Producers push ten times faster than consumers can drain. The queue grows…', send: [0,1,2,3,4,5].map(i => ({ path: ['p','q'], label: '', delay: i * 120 })).concat([{ path: ['q','c'], label: '', delay: 300 }]), badges: { q: '1,200 waiting' } },
             { cap: '…and grows.', send: [0,1,2,3,4,5].map(i => ({ path: ['p','q'], label: '', delay: i * 120 })).concat([{ path: ['q','c'], label: '', delay: 300 }]), badges: { q: '48,000 waiting' }, states: { q: 'warn' } },
             { cap: 'Backpressure: tell producers to slow down (or scale consumers, or shed load) before the queue falls over.', send: [{ path: ['q','p'], label: 'slow down', color: 'warn' }, { path: ['p','q'], label: '', delay: 800 }, { path: ['q','c'], label: '', delay: 900 }, { path: ['p','q'], label: '', delay: 1500 }, { path: ['q','c'], label: '', delay: 1600 }], badges: { q: '47,000 waiting' }, states: { q: 'warn' }, t: 3200 }] };
  S.timeout = { nodes: [N('o','Order Service',0,0), N('p','Payment Service',1,0)], edges: [['o','p']],
    frames: [{ cap: 'Call payment with a 3-second timeout.', send: [{ path: ['o','p'], label: 'charge' }], badges: { o: 'waiting 0 s' } }, { badges: { o: 'waiting 1 s' }, states: { p: 'warn' }, t: 700 }, { badges: { o: 'waiting 2 s' }, states: { p: 'warn' }, t: 700 }, { badges: { o: 'waiting 3 s' }, states: { p: 'fail' }, t: 700 },
             { cap: 'No answer in 3 seconds: give up, free the thread, return an error or retry. Never wait forever.', badges: { o: 'timed out' }, states: { o: 'warn', p: 'fail' }, t: 2600 }] };
  S.bulkhead = { nodes: [N('t','Traffic',0,1,'','client'), N('ck','Checkout pool',1,0,'20 threads'), N('se','Search pool',1,1,'20 threads'), N('re','Recommendation pool',1,2,'20 threads')], edges: [['t','ck'],['t','se'],['t','re']],
    frames: [{ cap: 'Each feature gets its own pool of threads and connections.', send: [{ path: ['t','ck'], label: '' }, { path: ['t','se'], label: '', delay: 200 }, { path: ['t','re'], label: '', delay: 400 }] }, { cap: 'Recommendations start hanging and exhaust their pool. Checkout and search keep their own threads and stay healthy.', states: { re: 'fail' }, badges: { re: '20/20 stuck' }, send: [{ path: ['t','ck'], label: '', color: 'ok' }, { path: ['t','se'], label: '', delay: 300, color: 'ok' }], t: 3000 }] };
  S.bluegreen = { nodes: [N('lb','Load balancer',1,0), N('b','Blue',0,1,'old app'), N('g','Green',2,1,'new app')], edges: [['lb','b'],['lb','g',{ hidden: true }]],
    frames: [{ cap: 'All traffic goes to Blue while Green is deployed and tested on the side.', send: [{ path: ['lb','b'], label: '' }, { path: ['lb','b'], label: '', delay: 400 }], states: { b: 'ok', g: 'warn' }, badges: { g: 'testing' } },
             { cap: 'Switch: the load balancer now points at Green. Blue stays up, so rolling back is one switch away.', edgesHide: ['lb>b'], edgesShow: ['lb>g'], states: { g: 'ok' }, badges: { b: 'standby' }, send: [{ path: ['lb','g'], label: '' }, { path: ['lb','g'], label: '', delay: 400 }], t: 2800 },
             { edgesShow: ['lb>b'], edgesHide: ['lb>g'], states: {}, badges: {}, t: 300 }] };
  S.canary = { nodes: [N('lb','Load balancer',1,0), N('v1','Version 1',0,1), N('v2','Version 2',2,1,'canary')], edges: [['lb','v1'],['lb','v2']],
    frames: [{ cap: '95% → Version 1, 5% → Version 2. Watch the metrics.', badges: { v1: '95%', v2: '5%' }, send: [0,1,2,3,4,5,6,7,8].map(i => ({ path: ['lb','v1'], label: '', delay: i * 150 })).concat([{ path: ['lb','v2'], label: '', delay: 700 }]) },
             { cap: 'Looks good: 50 / 50.', badges: { v1: '50%', v2: '50%' }, send: [0,1,2,3,4].map(i => ({ path: ['lb','v1'], label: '', delay: i * 300 })).concat([0,1,2,3,4].map(i => ({ path: ['lb','v2'], label: '', delay: i * 300 + 150 }))) },
             { cap: '100% → Version 2. A bad release would have hurt 5% of users, not everyone.', badges: { v1: '0%', v2: '100%' }, states: { v2: 'ok', v1: 'off' }, send: [0,1,2,3,4,5,6,7,8,9].map(i => ({ path: ['lb','v2'], label: '', delay: i * 150 })), t: 3000 }] };
  S.tls = { nodes: [N('c','Client',0,0,'','client'), N('s','Server',2,0)], edges: [['c','s',{ both: true, label: 'TLS: encrypted connection' }]],
    frames: [{ cap: 'Data in transit is scrambled: anyone on the network sees only ciphertext.', send: [{ path: ['c','s'], label: '🔒 a8f3…' }, { path: ['s','c'], label: '🔒 c91e…', delay: 800, color: 'ok' }] }] };
  S.hashing = { nodes: [N('i','"hello"',0,0,'','client'), N('h','hash',1,0,'one-way'), N('o','2cf24d…',2,0,'fixed size','mem')], edges: [['i','h'],['h','o']],
    frames: [{ cap: 'Any input, a fixed-size fingerprint. Easy to compute, infeasible to reverse.', send: [{ path: ['i','h','o'], label: '' }] }] };
  S.warehouse = { nodes: [N('db','Application databases',0,0,'','db'), N('pl','Data pipeline',1,0,'ETL / streaming'), N('wh','Data warehouse',2,0,'BigQuery / Snowflake','db'), N('bi','BI / analytics',3,0,'','client')], edges: [['db','pl'],['pl','wh'],['wh','bi']],
    frames: [{ cap: 'Transactional data is copied and reshaped into a warehouse built for big analytical queries.', send: [{ path: ['db','pl','wh'], label: 'rows' }, { path: ['bi','wh'], label: 'sales by country, 5 yrs', delay: 1800 }] }] };
  S.big = { nodes: [N('u','USER',2,0,'','client'), N('dns','DNS',2,1), N('cdn','CDN',2,2), N('lb','Load balancer',2,3), N('gw','API Gateway',2,4), N('us','User Service',0,5), N('os','Order Service',2,5), N('ss','Search Service',4,5), N('ca','Cache',0,6,'','mem'), N('db','Database',2,6,'','db'), N('se','Search Engine',4,6,'','mem'), N('mb','Message Broker',2,7,'','queue'), N('ps','Payment Service',0,8), N('es','Email Service',2,8), N('is','Inventory Service',4,8)],
    edges: [['u','dns'],['dns','cdn'],['cdn','lb'],['lb','gw'],['gw','us'],['gw','os'],['gw','ss'],['us','ca'],['os','db'],['ss','se'],['db','mb'],['mb','ps'],['mb','es'],['mb','is']],
    frames: [{ cap: 'A page load: DNS, CDN, load balancer, gateway, then the user service and its cache.', send: [{ path: ['u','dns','cdn','lb','gw','us','ca'], label: 'GET /me' }] },
             { cap: 'Placing an order: the order service writes to the database, which publishes an event…', send: [{ path: ['u','dns','cdn','lb','gw','os','db','mb'], label: 'POST /orders' }] },
             { cap: '…that fans out to payment, email and inventory in the background.', send: [{ path: ['mb','ps'], label: '' }, { path: ['mb','es'], label: '', delay: 200 }, { path: ['mb','is'], label: '', delay: 400 }] },
             { cap: 'A search goes to the search service and its index.', send: [{ path: ['u','dns','cdn','lb','gw','ss','se'], label: 'GET /search' }] }] };
  const chain = (steps) => ({ nodes: steps.map((s, i) => N('s' + i, s, 0, i, '', i % 2 ? 'ok' : 'warn', { w: 2 })), edges: steps.slice(1).map((_, i) => ['s' + i, 's' + (i + 1)]), frames: steps.map((s, i) => ({ cap: i % 2 ? 'Add the component that solves it.' : 'Name the problem first.', states: Object.fromEntries(steps.map((_, j) => ['s' + j, j < i ? (j % 2 ? 'ok' : 'warn') : j === i ? 'on' : 'off'])), t: 1300 })).concat([{ states: Object.fromEntries(steps.map((_, j) => ['s' + j, j % 2 ? 'ok' : 'warn'])), cap: 'Problem → component. Never the other way round.', t: 2600 }]) });
  S.chain1 = chain(['One server cannot handle traffic', 'Add horizontal scaling', 'Need to distribute traffic', 'Add load balancer']);
  S.chain2 = chain(['Database receives too many repeated reads', 'Add cache']);
  S.chain3 = chain(['Images load slowly around the world', 'Add CDN']);
  S.chain4 = chain(['Background work makes requests slow', 'Add message queue']);
  S.chain5 = chain(['Database cannot handle read traffic', 'Add read replicas']);
  S.chain6 = chain(['Database becomes too large for one machine', 'Introduce partitioning/sharding']);
  S.chain7 = chain(['Microservices depend on unreliable networks', 'Add timeout + retry + circuit breaker']);

  window.ANIM_SPECS = S;
})();
